# Generated by Django 5.1.5 on 2025-01-19 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wallpaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='wallpapers')),
                ('image_format', models.CharField(blank=True, help_text='e.g. png', max_length=4)),
                ('image_size', models.IntegerField(blank=True, help_text='size in bytes')),
                ('width', models.IntegerField(blank=True)),
                ('height', models.IntegerField(blank=True)),
                ('aspect_ratio', models.CharField(blank=True, help_text='e.g. 16:9', max_length=6)),
                ('hash', models.CharField(blank=True, max_length=32)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='thumbnails')),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('wallpaper', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail', to='wdb_wallpaper.wallpaper')),
            ],
        ),
    ]
