# Generated by Django 5.1.5 on 2025-01-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdb_wallpaper', '0002_wallpaper_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='hash',
            field=models.CharField(blank=True, max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='wallpaper',
            name='tags',
            field=models.ManyToManyField(blank=True, to='wdb_wallpaper.tag'),
        ),
    ]
