# Generated by Django 5.1.5 on 2025-01-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdb_wallpaper', '0003_alter_wallpaper_hash_alter_wallpaper_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='auto_generated',
            field=models.BooleanField(default=False),
        ),
    ]
