# Generated by Django 5.1.5 on 2025-01-26 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdb_wallpaper', '0004_tag_auto_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='ai_description',
            field=models.TextField(blank=True, help_text='AI generated description about image', null=True),
        ),
    ]
