# Generated by Django 5.1.5 on 2025-02-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdb_wallpaper', '0006_remove_wallpaper_ai_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallpaper',
            name='chromadb_description_added',
            field=models.BooleanField(default=False),
        ),
    ]
