# Generated by Django 5.1.5 on 2025-02-01 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdb_wallpaper', '0007_wallpaper_chromadb_description_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='chromadb_description_added',
            field=models.BooleanField(default=False, help_text='If added to ChromaDB'),
        ),
    ]
