# Generated by Django 5.1.5 on 2025-03-16 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdb_wallpaper', '0008_alter_wallpaper_chromadb_description_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallpaper',
            name='chromadb_description_added',
        ),
    ]
