# Generated by Django 5.1.11 on 2025-07-23 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wdb_wallpaper', '0009_remove_wallpaper_chromadb_description_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='auto_generated',
        ),
    ]
