# Generated by Django 5.1.11 on 2025-07-26 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wdb_wallpaper', '0010_remove_tag_auto_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallpaper',
            name='aspect_ratio',
            field=models.CharField(blank=True, help_text='e.g. 16:9', max_length=10),
        ),
    ]
